source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

project 'CoreDAO.xcodeproj'
workspace 'Workspace.xcworkspace'

realmVersion = '~> 3.0'

target :CoreDAOExample do
    pod 'RealmSwift', realmVersion
end

target :CoreDAO do
    pod 'RealmSwift', realmVersion
end
