source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

xcodeproj 'CoreDAO.xcodeproj'
workspace 'Workspace.xcworkspace'


target :CoreDAOExample do
    xcodeproj 'CoreDAO.xcodeproj'
	pod 'RealmSwift'
end

target :CoreDAO do
    xcodeproj 'CoreDAO.xcodeproj'
    pod 'RealmSwift'
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
end
