source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

xcodeproj 'CoreDAO.xcodeproj'
workspace 'Workspace.xcworkspace'


target :CoreDAOExample do
    xcodeproj 'CoreDAO.xcodeproj'
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
	pod 'RealmSwift', :git => "https://github.com/realm/realm-cocoa", :branch => "master", :submodules => true
end

target :CoreDAO do
    xcodeproj 'CoreDAO.xcodeproj'
    pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', :submodules => true
    pod 'RealmSwift', :git => "https://github.com/realm/realm-cocoa", :branch => "master", :submodules => true
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end

end
